//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accudelta.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fund> Fund { get; set; }
        public virtual DbSet<FundValues> FundValues { get; set; }
        public virtual DbSet<V_FundWithLastValue> V_FundWithLastValue { get; set; }
    
        public virtual ObjectResult<FundsPaginated_Result> FundsPaginated(Nullable<int> pageNumber, Nullable<int> rowspPage)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var rowspPageParameter = rowspPage.HasValue ?
                new ObjectParameter("RowspPage", rowspPage) :
                new ObjectParameter("RowspPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FundsPaginated_Result>("FundsPaginated", pageNumberParameter, rowspPageParameter);
        }
    }
}
